# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 1.11.4 on 2017-09-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0002_auto_20170715_0655"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="send_mail",
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
    ]
