# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 1.11.5 on 2017-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0003_auto_20170908_0548"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpermission",
            name="is_reviewer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
    ]
