# Generated by Django 1.11.6 on 2017-10-23 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0007_user_code"),
    ]

    operations = []
