# Generated by Django 2.0.1 on 2018-01-22 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0012_user_is_administrator"),
    ]

    operations = []
