# Generated by Django 2.0.8 on 2018-08-21 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0018_auto_20180812_1523"),
    ]

    operations = []
