# Generated by Django 3.1.4 on 2021-01-30 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0023_speakerinformation_target_group"),
    ]

    operations = []
