# SPDX-FileCopyrightText: 2024-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.1.2 on 2024-10-12 18:42

from django.db import migrations, models

import pretalx.person.models.user


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0027_created_updated_everywhere"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_thumbnail",
            field=models.ImageField(
                null=True, upload_to=pretalx.person.models.user.avatar_path
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_thumbnail_tiny",
            field=models.ImageField(
                null=True, upload_to=pretalx.person.models.user.avatar_path
            ),
        ),
    ]
