# Generated by Django 5.2.3 on 2025-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0031_migrate_auth_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerprofile",
            name="internal_notes",
            field=models.TextField(null=True),
        ),
    ]
