# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.2.3 on 2025-09-29 10:12
from django.db import migrations, models

import pretalx.common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0031_migrate_auth_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerprofile",
            name="internal_notes",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="speakerprofile",
            name="biography",
            field=pretalx.common.models.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name="userapitoken",
            name="expires",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
    ]
