# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.2 on 2026-02-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0033_usereventpreferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerprofile",
            name="code",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="name",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
