# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.2 on 2026-02-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0041_event_og_image"),
        ("person", "0035_populate_speakerprofile_name_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakerprofile",
            name="code",
            field=models.CharField(max_length=16),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="speakerprofile",
            unique_together={("event", "code"), ("event", "user")},
        ),
    ]
