# Generated by Django 6.0.4 on 2026-05-07 06:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("person", "0036_speakerprofile_finalize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Your email address will be used for password resets and notification about your event/proposals.",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="person_user_email_unique_ci",
                violation_error_message="Please choose a different email address.",
            ),
        ),
    ]
