# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.2 on 2026-02-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0038_populate_profile_pictures"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar_thumbnail",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar_thumbnail_tiny",
        ),
        migrations.RemoveField(
            model_name="user",
            name="get_gravatar",
        ),
    ]
