# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.7 on 2026-07-30 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("person", "0044_user_person_user_email_upper_idx")]

    operations = [
        migrations.AddField(
            model_name="speakerprofile",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="guid",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="invitation_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="invitation_token",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="locale",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="origin",
            field=models.CharField(default="cfp", max_length=8),
        ),
        migrations.AlterField(
            model_name="profilepicture",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
