# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.7 on 2026-08-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("person", "0046_speakerprofile_guid_backfill")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_state",
            field=models.CharField(default="unverified", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_email_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
