# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.1 on 2026-09-04 15:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0046_organiser_organiser_slug_lower_unique"),
        ("person", "0048_user_verification_state_legacy_backfill"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="speakerprofile",
            index=models.Index(
                django.db.models.functions.text.Upper("code"),
                name="speakerprofile_code_upper_idx",
            ),
        )
    ]
