# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.1 on 2026-09-10 11:52

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("person", "0049_speakerprofile_speakerprofile_code_upper_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                django.db.models.functions.text.Upper("code"),
                name="person_user_code_upper_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                condition=models.Q(("pw_reset_token__isnull", False)),
                fields=["pw_reset_token"],
                name="person_user_pw_reset_idx",
            ),
        ),
    ]
