# Generated by Django 1.11.4 on 2017-08-20 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0001_initial"),
    ]

    operations = []
