# SPDX-FileCopyrightText: 2023 pretalx contributors <https://github.com/pretalx/pretalx/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 1.11.4 on 2017-09-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0003_auto_20170830_1813"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="code",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
