# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 1.11.4 on 2017-09-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0005_auto_20170902_0800"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
