# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 1.11.6 on 2017-10-06 16:18

import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0009_auto_20171004_0819"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="help_text",
            field=i18nfield.fields.I18nCharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="target",
            field=models.CharField(default="submission", max_length=10),
        ),
        migrations.AlterField(
            model_name="question",
            name="variant",
            field=models.CharField(default="string", max_length=15),
        ),
    ]
