# SPDX-FileCopyrightText: 2023 pretalx contributors <https://github.com/pretalx/pretalx/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 1.11.6 on 2017-10-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0011_submission_invitation_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
