# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 1.11.7 on 2017-11-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0014_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="contains_personal_data",
            field=models.BooleanField(default=True),
        ),
    ]
