# Generated by Django 2.0.1 on 2018-01-15 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0016_auto_20171114_1251"),
    ]

    operations = []
