# SPDX-FileCopyrightText: 2018-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 2.0.1 on 2018-02-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0018_remove_submissiontype_max_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontype",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
