# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 2.0.1 on 2018-02-05 19:50

from django.db import migrations, models

import pretalx.submission.models.submission


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0019_submissiontype_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pretalx.submission.models.submission.submission_image_path,
            ),
        ),
    ]
