# SPDX-FileCopyrightText: 2023 pretalx contributors <https://github.com/pretalx/pretalx/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 1.11.7 on 2018-01-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0022_submission_review_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
