# Generated by Django 2.0.3 on 2018-06-19 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0023_submission_is_featured"),
    ]

    operations = []
