# SPDX-FileCopyrightText: 2018-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 2.0.8 on 2018-08-12 21:47

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0026_auto_20180811_1827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=i18nfield.fields.I18nCharField(max_length=800),
        ),
    ]
