# SPDX-FileCopyrightText: 2018-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 2.0.8 on 2018-09-22 10:11

import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0027_auto_20180812_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfp",
            name="text",
            field=i18nfield.fields.I18nTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="review",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="submission",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
