# Generated by Django 2.1.5 on 2019-02-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0030_auto_20181209_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='submission_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='submission.SubmissionType'),
        ),
    ]
