# Generated by Django 2.1.5 on 2019-01-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0030_auto_20181209_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='available_count',
            field=models.PositiveIntegerField(default=1, help_text='How often are you available to hold your talk.Currently only editable by the organiser.', verbose_name='Available Count'),
        ),
    ]
