# Generated by Django 2.1.5 on 2019-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0031_submission_available_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='available_count',
            new_name='slot_count'
        ),
        migrations.AlterField(
            model_name='submission',
            name='slot_count',
            field=models.PositiveIntegerField(default=1, help_text='How many times this talk will be held. Currently only editable by the organiser.', verbose_name='Slot Count'),
        ),
    ]
