# SPDX-FileCopyrightText: 2023 pretalx contributors <https://github.com/pretalx/pretalx/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.1.5 on 2019-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0032_question_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="slot_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
