# SPDX-FileCopyrightText: 2019-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 2.1.5 on 2019-03-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0019_auto_20190224_0856"),
        ("submission", "0034_submission_internal_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewPhase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=False)),
                ("can_review", models.BooleanField(default=True)),
                (
                    "can_see_other_reviews",
                    models.CharField(default="after_review", max_length=12),
                ),
                ("can_see_speaker_names", models.BooleanField(default=True)),
                ("can_change_submission_state", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_phases",
                        to="event.Event",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
            },
        ),
    ]
