# Generated by Django 2.1.5 on 2019-03-07 23:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0035_reviewphase"),
    ]

    operations = []
