# Generated by Django 2.2.1 on 2019-05-01 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0039_submission_created"),
    ]

    operations = []
