# Generated by Django 2.2.5 on 2019-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0040_submission_created_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_example',
            field=models.BooleanField(default=False),
        ),
    ]
