# Generated by Django 2.2.5 on 2019-09-04 12:09

from django.db import migrations
import i18nfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0040_submission_created_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfp',
            name='help_text_abstract',
            field=i18nfield.fields.I18nTextField(blank=True, default='A brief description of your talk. It should be a summary of a longer description if provided. You can use [Markdown](https://docs.pretalx.org/en/latest/user/markdown.html) here. This content will be shown publicly.', null=True),
        ),
        migrations.AddField(
            model_name='cfp',
            name='help_text_additional_speaker',
            field=i18nfield.fields.I18nTextField(blank=True, default='If you have a co-speaker, please add their email address here, and we will invite them to create an account. If you have more than one co-speaker, you can add more speakers after finishing the submission process.', null=True),
        ),
        migrations.AddField(
            model_name='cfp',
            name='help_text_description',
            field=i18nfield.fields.I18nTextField(blank=True, default='A long description of your talk. You can use [Markdown](https://docs.pretalx.org/en/latest/user/markdown.html) here. This content will be shown publicly.', null=True),
        ),
        migrations.AddField(
            model_name='cfp',
            name='help_text_image',
            field=i18nfield.fields.I18nTextField(blank=True, default='Use this if you want an illustration to go with your submission. This content will be shown publicly.', null=True),
        ),
        migrations.AddField(
            model_name='cfp',
            name='help_text_notes',
            field=i18nfield.fields.I18nTextField(blank=True, default="These notes are meant for the organiser and won't be made public.", null=True),
        ),
        migrations.AddField(
            model_name='cfp',
            name='help_text_slot_count',
            field=i18nfield.fields.I18nTextField(blank=True, default='How many times this talk will be held.', null=True),
        ),
        migrations.AddField(
            model_name='cfp',
            name='help_text_track',
            field=i18nfield.fields.I18nTextField(blank=True, null=True),
        ),
    ]
