# SPDX-FileCopyrightText: 2018-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 3.0.3 on 2020-03-01 19:25

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0044_submission_anonymised_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="help_text",
            field=i18nfield.fields.I18nCharField(blank=True, max_length=800, null=True),
        ),
    ]
