# Generated by Django 3.1 on 2020-09-23 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0049_review_score_categories"),
    ]

    operations = []
