# SPDX-FileCopyrightText: 2023 pretalx contributors <https://github.com/pretalx/pretalx/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 3.1 on 2020-09-24 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0050_migrate_review_scores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="override_vote",
        ),
    ]
