# SPDX-FileCopyrightText: 2018-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 3.1 on 2020-10-10 13:07

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models

import pretalx.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0024_remove_team_review_override_votes"),
        ("submission", "0051_remove_review_override_vote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("tag", models.CharField(max_length=50)),
                ("description", i18nfield.fields.I18nTextField()),
                ("color", models.CharField(max_length=7)),
                ("public", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="event.event",
                    ),
                ),
            ],
            bases=(pretalx.common.models.mixins.LogMixin, models.Model),
        ),
        migrations.AddField(
            model_name="submission",
            name="tags",
            field=models.ManyToManyField(
                related_name="submissions", to="submission.Tag"
            ),
        ),
    ]
