# SPDX-FileCopyrightText: 2023 pretalx contributors <https://github.com/pretalx/pretalx/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 3.1 on 2020-10-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0053_reviewphase_can_tag_submissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewscorecategory",
            name="limit_tracks",
            field=models.ManyToManyField(to="submission.Track"),
        ),
    ]
