# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 3.1 on 2020-10-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0053_reviewphase_can_tag_submissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewscorecategory",
            name="limit_tracks",
            field=models.ManyToManyField(to="submission.Track"),
        ),
    ]
