# Generated by Django 3.1 on 2020-11-10 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0054_reviewscorecategory_limit_tracks"),
    ]

    operations = []
