# Generated by Django 3.1.4 on 2021-06-24 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0057_question_required_freeze"),
    ]

    operations = []
