# SPDX-FileCopyrightText: 2018-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 3.2.4 on 2021-10-25 14:29

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0059_remove_question_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeroption",
            name="answer",
            field=i18nfield.fields.I18nCharField(),
        ),
    ]
