# Generated by Django 3.2.4 on 2021-12-02 17:14
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0061_cfp_settings"),
    ]

    operations = []
