# Generated by Django 3.2.10 on 2022-01-04 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0063_submission_pending_state"),
    ]

    operations = []
