# Generated by Django 3.2.16 on 2022-12-24 00:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0069_resource_links"),
    ]

    operations = []
