# SPDX-FileCopyrightText: 2019-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 4.2 on 2023-06-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0071_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewscore",
            name="label",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
