# SPDX-FileCopyrightText: 2023 pretalx contributors <https://github.com/pretalx/pretalx/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.2 on 2023-06-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0071_alter_review_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewscore",
            name="label",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
