# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 4.2.9 on 2024-02-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0074_created_updated_everywhere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="link",
            field=models.URLField(max_length=400, null=True),
        ),
    ]
