# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.1.2 on 2024-10-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0076_submissionfavourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeroption",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
