# Generated by Django 5.1.3 on 2025-04-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0078_submissioncomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
