# SPDX-FileCopyrightText: 2025-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.1.7 on 2025-05-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0039_alter_teaminvite_token"),
        ("submission", "0080_speakerrole_alter_submission_speakers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("event", "tag")},
        ),
    ]
