# Generated by Django 5.1.7 on 2025-05-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0080_speakerrole_alter_submission_speakers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("event", "tag")},
        ),
    ]
