# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.2.3 on 2025-07-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0081_alter_tag_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="icon",
            field=models.CharField(max_length=9, null=True),
        ),
    ]
