# SPDX-FileCopyrightText: 2019-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.2.3 on 2025-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0082_question_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="submitteraccesscode",
            name="internal_notes",
            field=models.TextField(null=True),
        ),
    ]
