# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.2.6 on 2025-09-29 13:42
from django.db import migrations, models

import pretalx.common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0083_submitteraccesscode_internal_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfp",
            name="opening",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cfp",
            name="deadline",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cfp",
            name="opening",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="deadline",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="freeze_after",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="max_date",
            field=pretalx.common.models.fields.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="max_datetime",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="min_date",
            field=pretalx.common.models.fields.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="min_datetime",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewphase",
            name="end",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewphase",
            name="start",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submissiontype",
            name="deadline",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submitteraccesscode",
            name="valid_until",
            field=pretalx.common.models.fields.DateTimeField(blank=True, null=True),
        ),
    ]
