# Generated by Django 5.2.6 on 2025-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0083_submitteraccesscode_internal_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfp",
            name="opening",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
