# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.2.3 on 2025-09-29 16:36
from django.db import migrations, models

import pretalx.common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0084_cfp_opening"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="review",
            field=pretalx.common.models.fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=pretalx.common.models.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="abstract",
            field=pretalx.common.models.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="description",
            field=pretalx.common.models.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="notes",
            field=pretalx.common.models.fields.MarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name="submissioncomment",
            name="text",
            field=pretalx.common.models.fields.MarkdownField(),
        ),
    ]
