# Generated by Django 5.2.3 on 2025-09-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0084_cfp_opening"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
