# Generated by Django 5.2.7 on 2025-10-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0085_resource_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="icon",
            field=models.CharField(default=None, max_length=9, null=True),
        ),
    ]
