# SPDX-FileCopyrightText: 2025-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.2.8 on 2025-11-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0040_alter_event_settingsstore_unique_together"),
        ("submission", "0086_alter_question_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="limit_teams",
            field=models.ManyToManyField(related_name="+", to="event.team"),
        ),
    ]
