# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0 on 2026-01-15 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0040_alter_event_settingsstore_unique_together"),
        ("submission", "0088_submission_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeroption",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="You can enter any value here to make it easier to match the data with other sources. If you do not input one, we will generate one automatically.",
                max_length=190,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The identifier may only contain letters, numbers, dots, dashes, and underscores.",
                        regex="^[a-zA-Z0-9.\\-_]+$",
                    )
                ],
                verbose_name="Internal identifier",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="You can enter any value here to make it easier to match the data with other sources. If you do not input one, we will generate one automatically.",
                max_length=190,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The identifier may only contain letters, numbers, dots, dashes, and underscores.",
                        regex="^[a-zA-Z0-9.\\-_]+$",
                    )
                ],
                verbose_name="Internal identifier",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answeroption", unique_together={("question", "identifier")}
        ),
        migrations.AlterUniqueTogether(
            name="question", unique_together={("event", "identifier")}
        ),
    ]
