# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django on 2025-11-02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0088_submission_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="hide_until_event_day",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, this resource will only be visible on or after the day of the session.",
                verbose_name="Hide until event day",
            ),
        ),
    ]
