# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0 on 2026-01-15 09:01

from django.db import migrations
from django.db.models import CharField, Value
from django.db.models.functions import Cast, Concat


def populate_question_identifiers(apps, schema_editor):
    Question = apps.get_model("submission", "Question")
    AnswerOption = apps.get_model("submission", "AnswerOption")

    Question.objects.filter(identifier__isnull=True).update(
        identifier=Concat(Value("Q"), Cast("pk", CharField()))
    )
    AnswerOption.objects.filter(identifier__isnull=True).update(
        identifier=Concat(Value("O"), Cast("pk", CharField()))
    )


def reverse_populate(apps, schema_editor):
    Question = apps.get_model("submission", "Question")
    AnswerOption = apps.get_model("submission", "AnswerOption")

    Question.objects.all().update(identifier=None)
    AnswerOption.objects.all().update(identifier=None)


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0089_add_question_identifier"),
    ]

    operations = [
        migrations.RunPython(populate_question_identifiers, reverse_populate),
    ]
