# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0 on 2026-01-15 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0090_populate_question_identifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answeroption",
            name="identifier",
            field=models.CharField(
                help_text="You can enter any value here to make it easier to match the data with other sources. If you do not input one, we will generate one automatically.",
                max_length=190,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The identifier may only contain letters, numbers, dots, dashes, and underscores.",
                        regex="^[a-zA-Z0-9.\\-_]+$",
                    )
                ],
                verbose_name="Internal identifier",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="identifier",
            field=models.CharField(
                help_text="You can enter any value here to make it easier to match the data with other sources. If you do not input one, we will generate one automatically.",
                max_length=190,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The identifier may only contain letters, numbers, dots, dashes, and underscores.",
                        regex="^[a-zA-Z0-9.\\-_]+$",
                    )
                ],
                verbose_name="Internal identifier",
            ),
        ),
    ]
