# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.1

import logging

from django.db import migrations
from django_scopes import scopes_disabled

logger = logging.getLogger(__name__)


def delete_soft_deleted_submissions(apps, schema_editor):
    with scopes_disabled():
        _delete_soft_deleted_submissions(apps)


def _delete_soft_deleted_submissions(apps):
    Submission = apps.get_model("submission", "Submission")
    deleted_ids = list(
        Submission.objects.filter(state="deleted").values_list("id", flat=True)
    )

    if not deleted_ids:
        logger.info("No soft-deleted submissions found, nothing to do")
        return

    logger.info(
        f"Found {len(deleted_ids)} soft-deleted submissions to permanently delete"
    )

    Answer = apps.get_model("submission", "Answer")
    Resource = apps.get_model("submission", "Resource")
    TalkSlot = apps.get_model("schedule", "TalkSlot")

    # Step 1: Delete pretalx-native related objects with PROTECT foreign keys first
    slots = TalkSlot.objects.filter(submission_id__in=deleted_ids)
    slot_count = slots.count()
    if slot_count:
        logger.info(f"Deleting {slot_count} TalkSlot objects")
        slots.delete()

    answers = Answer.objects.filter(submission_id__in=deleted_ids)
    answer_count = answers.count()
    review_answers = Answer.objects.filter(review__submission_id__in=deleted_ids)
    review_answer_count = review_answers.count()
    if answer_count:
        logger.info(f"Deleting {answer_count} Answer objects (submission answers)")
        answers.delete()
    if review_answer_count:
        logger.info(f"Deleting {review_answer_count} Answer objects (review answers)")
        review_answers.delete()

    resources = Resource.objects.filter(submission_id__in=deleted_ids)
    resource_count = resources.count()
    if resource_count:
        logger.info(f"Deleting {resource_count} Resource objects")
        resources.delete()

    # Step 2: Discover and delete any other related objects (e.g., from plugins)
    from django.apps import apps as django_apps
    from django.db.models.fields.related import ForeignKey

    handled_models = {
        "schedule.TalkSlot",
        "submission.Answer",
        "submission.Resource",
        "submission.Review",  # CASCADE
    }

    logger.info("Scanning for plugin models with Submission foreign keys...")
    found_plugin_relations = False

    for model in django_apps.get_models():
        if model._meta.label in handled_models:
            continue

        for field in model._meta.get_fields():
            if not isinstance(field, ForeignKey):
                continue

            if field.related_model._meta.label != "submission.Submission":
                continue

            field_name = field.name

            try:
                related_qs = model.objects.filter(
                    **{f"{field_name}_id__in": deleted_ids}
                )
                count = related_qs.count()
                if count > 0:
                    found_plugin_relations = True
                    logger.info(
                        f"Deleting {count} {model._meta.label} objects "
                        f"(plugin model, field: {field_name})"
                    )
                    related_qs.delete()
            except Exception as e:
                logger.warning(
                    f"Could not delete {model._meta.label}.{field_name} objects: {e}"
                )

    if not found_plugin_relations:
        logger.info("No plugin-related objects found")

    # Step 3: Delete the submissions themselves
    logger.info(f"Deleting {len(deleted_ids)} submissions")
    try:
        Submission.objects.filter(id__in=deleted_ids).delete()
        logger.info(
            f"Successfully permanently deleted {len(deleted_ids)} "
            "previously soft-deleted submissions"
        )
    except Exception as e:
        error_msg = str(e)
        logger.error(
            f"Failed to delete soft-deleted submissions: {error_msg}\n"
            "This is likely due to database tables from plugins that reference "
            "Submission but are not registered in Django. You may need to:\n"
            "1. Install the plugin that owns the referencing table, OR\n"
            "2. Manually delete the referencing records from the database"
        )
        raise


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0091_question_identifier_unique"),
        ("schedule", "0018_talkslot_slot_type"),
    ]

    operations = [
        migrations.RunPython(
            delete_soft_deleted_submissions, migrations.RunPython.noop, elidable=True
        ),
    ]
