# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.1

import logging

from django.db import migrations
from django_scopes import scopes_disabled

logger = logging.getLogger(__name__)


def delete_soft_deleted_submissions(apps, schema_editor):
    with scopes_disabled():
        _delete_soft_deleted_submissions(apps)


def _delete_soft_deleted_submissions(apps):
    Submission = apps.get_model("submission", "Submission")
    deleted_ids = list(
        Submission.objects.filter(state="deleted").values_list("id", flat=True)
    )

    if not deleted_ids:
        logger.info("No soft-deleted submissions found, nothing to do")
        return

    logger.info(
        "Found %d soft-deleted submissions to permanently delete", len(deleted_ids)
    )

    Answer = apps.get_model("submission", "Answer")
    Resource = apps.get_model("submission", "Resource")
    TalkSlot = apps.get_model("schedule", "TalkSlot")

    # Step 1: Delete pretalx-native related objects with PROTECT foreign keys first
    slots = TalkSlot.objects.filter(submission_id__in=deleted_ids)
    slot_count = slots.count()
    if slot_count:
        logger.info("Deleting %d TalkSlot objects", slot_count)
        slots.delete()

    answers = Answer.objects.filter(submission_id__in=deleted_ids)
    answer_count = answers.count()
    review_answers = Answer.objects.filter(review__submission_id__in=deleted_ids)
    review_answer_count = review_answers.count()
    if answer_count:
        logger.info("Deleting %d Answer objects (submission answers)", answer_count)
        answers.delete()
    if review_answer_count:
        logger.info("Deleting %d Answer objects (review answers)", review_answer_count)
        review_answers.delete()

    resources = Resource.objects.filter(submission_id__in=deleted_ids)
    resource_count = resources.count()
    if resource_count:
        logger.info("Deleting %d Resource objects", resource_count)
        resources.delete()

    # Step 2: Discover and delete any other related objects (e.g., from plugins)
    from django.apps import apps as django_apps  # noqa: PLC0415
    from django.db.models.fields.related import ForeignKey  # noqa: PLC0415

    handled_models = {
        "schedule.TalkSlot",
        "submission.Answer",
        "submission.Resource",
        "submission.Review",  # CASCADE
    }

    logger.info("Scanning for plugin models with Submission foreign keys...")
    found_plugin_relations = False

    for model in django_apps.get_models():
        if model._meta.label in handled_models:
            continue

        for field in model._meta.get_fields():
            if not isinstance(field, ForeignKey):
                continue

            if field.related_model._meta.label != "submission.Submission":
                continue

            field_name = field.name

            try:
                related_qs = model.objects.filter(
                    **{f"{field_name}_id__in": deleted_ids}
                )
                count = related_qs.count()
                if count > 0:
                    found_plugin_relations = True
                    logger.info(
                        "Deleting %d %s objects (plugin model, field: %s)",
                        count,
                        model._meta.label,
                        field_name,
                    )
                    related_qs.delete()
            except Exception as e:
                logger.warning(
                    "Could not delete %s.%s objects: %s",
                    model._meta.label,
                    field_name,
                    e,
                )

    if not found_plugin_relations:
        logger.info("No plugin-related objects found")

    # Step 3: Delete the submissions themselves
    logger.info("Deleting %d submissions", len(deleted_ids))
    try:
        Submission.objects.filter(id__in=deleted_ids).delete()
        logger.info(
            "Successfully permanently deleted %d previously soft-deleted submissions",
            len(deleted_ids),
        )
    except Exception as e:
        error_msg = str(e)
        logger.error(
            "Failed to delete soft-deleted submissions: %s\n"
            "This is likely due to database tables from plugins that reference "
            "Submission but are not registered in Django. You may need to:\n"
            "1. Install the plugin that owns the referencing table, OR\n"
            "2. Manually delete the referencing records from the database",
            error_msg,
        )
        raise


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0091_question_identifier_unique"),
        ("schedule", "0018_talkslot_slot_type"),
    ]

    operations = [
        migrations.RunPython(
            delete_soft_deleted_submissions, migrations.RunPython.noop, elidable=True
        ),
    ]
