# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.4 on 2026-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0041_event_og_image"),
        ("submission", "0103_submission_draft_additional_speakers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="tag", unique_together=set()),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("event", "tag"), name="unique_tag_per_event"
            ),
        ),
    ]
