# Generated by Django 6.0.5 on 2026-05-11 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("submission", "0104_unique_tag_per_event")]

    operations = [migrations.RemoveField(model_name="reviewphase", name="position")]
