# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.5 on 2026-05-20 12:09

import django.db.models.deletion
import rules.contrib.models
from django.db import migrations, models

import pretalx.common.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0041_attendeeprofile"),
        ("submission", "0105_remove_reviewphase_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="attendee_signup_capacity",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="attendee_signup_required",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="submissiontype",
            name="attendee_signup_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="track",
            name="attendee_signup_required",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AttendeeSignup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("state", models.CharField(default="confirmed", max_length=9)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="person.attendeeprofile",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendee_signups",
                        to="submission.submission",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
                "unique_together": {("submission", "attendee")},
            },
            bases=(
                pretalx.common.models.mixins.OrderedModel,
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
    ]
