# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.1 on 2026-09-01 12:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0045_event_event_slug_upper_idx_and_more"),
        ("submission", "0110_question_option_limits"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="tag", name="unique_tag_per_event"),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("tag"),
                models.F("event"),
                name="unique_tag_per_event",
            ),
        ),
    ]
