# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.1 on 2026-09-04 15:49

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0046_organiser_organiser_slug_lower_unique"),
        ("person", "0049_speakerprofile_speakerprofile_code_upper_idx"),
        ("submission", "0111_remove_tag_unique_tag_per_event_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                django.db.models.functions.text.Upper("code"),
                name="submission_code_upper_idx",
            ),
        )
    ]
