language: python
sudo: false
python: 3.6
install:
  - pip install -U pip setuptools wheel typing
  - pip install -r src/requirements.txt
  - pip install -r src/requirements/dev.txt -r src/requirements/fancy.txt
script:
  - cd src/
  - flake8 .
  - py.test tests/
