# Generated by Django 1.11.4 on 2017-08-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_auto_20170715_0655"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="update_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="mail.MailTemplate",
            ),
        ),
    ]
