# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 1.11.7 on 2017-11-11 15:32

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_event_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="landing_page_text",
            field=i18nfield.fields.I18nTextField(blank=True, null=True),
        ),
    ]
