# Generated by Django 2.0.1 on 2018-01-26 15:59

from django.db import migrations, models
import django.db.models.deletion
import i18nfield.fields
import pretalx.common.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_landing_page_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Event start date')),
                ('title', i18nfield.fields.I18nCharField(max_length=200, verbose_name='Title')),
                ('description', i18nfield.fields.I18nTextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('is_public', models.BooleanField(default=True, verbose_name='Event is public')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_events', to='event.Event')),
            ],
            options={
                'ordering': ('datetime',),
            },
            bases=(pretalx.common.mixins.models.LogMixin, models.Model),
        ),
    ]
