# Generated by Django 2.0.3 on 2018-04-07 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0013_auto_20180407_0817"),
    ]

    operations = []
