# SPDX-FileCopyrightText: 2018-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 2.0.3 on 2018-05-30 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0014_auto_20180407_0826"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="subtitle",
        ),
    ]
