# Generated by Django 2.1.5 on 2019-02-24 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0018_auto_20190223_1543"),
    ]

    operations = []
