# Generated by Django 2.2.5 on 2019-09-17 10:47

from django.db import migrations, models


def submission_locale_array_default_to_locale_array(apps, schema_editor):
    Event = apps.get_model("event", "Event")
    for event in Event.objects.all().iterator():
        event.submission_locale_array = event.locale_array


def dummy_reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20190429_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='submission_locale_array',
            field=models.TextField(default='en'),
        ),
        migrations.RunPython(
            submission_locale_array_default_to_locale_array,
            dummy_reverse_func
        ),
    ]
