# Generated by Django 2.2.5 on 2019-09-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20190429_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='submission_locale_array',
            field=models.TextField(default='en'),
        ),
    ]
