# Generated by Django 3.0.5 on 2020-07-26 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0022_auto_20200124_1213"),
    ]

    operations = []
