# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 3.1.4 on 2020-12-13 23:27

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0024_remove_team_review_override_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="featured_sessions_text",
            field=i18nfield.fields.I18nTextField(null=True),
        ),
    ]
