# Generated by Django 3.2.4 on 2021-12-02 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0028_custom_event_data"),
    ]

    operations = []
