# Generated by Django 3.2.16 on 2022-12-23 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0030_event_content_locale_array"),
    ]

    operations = []
