# Generated by Django 4.2.4 on 2023-09-17 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0032_alter_event_timezone"),
    ]

    operations = []
