# Generated by Django 4.2.4 on 2023-09-21 10:02
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0033_chinese_locale_codes"),
    ]

    operations = []
