# SPDX-FileCopyrightText: 2024-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.1.2 on 2024-10-12 18:42

from django.db import migrations, models

import pretalx.event.models.event


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0035_created_updated_everywhere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="header_image",
            field=models.ImageField(
                null=True, upload_to=pretalx.event.models.event.event_logo_path
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="logo",
            field=models.ImageField(
                null=True, upload_to=pretalx.event.models.event.event_logo_path
            ),
        ),
    ]
