# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.1.7 on 2025-05-04 01:06

from django.db import migrations, models

import pretalx.event.models.organiser


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0038_eventextralink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teaminvite",
            name="token",
            field=models.CharField(
                default=pretalx.event.models.organiser.generate_invite_token,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
