# SPDX-FileCopyrightText: 2025-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 5.2.3 on 2025-09-01 13:45

from django.db import migrations
from hierarkey.utils import CleanHierarkeyDuplicates

import pretalx.common.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0039_alter_teaminvite_token"),
    ]

    operations = [
        CleanHierarkeyDuplicates("Event_SettingsStore"),
        migrations.AlterUniqueTogether(
            name="event_settingsstore",
            unique_together={("object", "key")},
        ),
        migrations.AlterField(
            model_name="event",
            name="date_from",
            field=pretalx.common.models.fields.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_to",
            field=pretalx.common.models.fields.DateField(),
        ),
    ]
