# Generated by Django 5.2.3 on 2025-09-01 13:45

from django.db import migrations
from hierarkey.utils import CleanHierarkeyDuplicates


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0039_alter_teaminvite_token"),
    ]

    operations = [
        CleanHierarkeyDuplicates("Event_SettingsStore"),
        migrations.AlterUniqueTogether(
            name="event_settingsstore",
            unique_together={("object", "key")},
        ),
    ]
