# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.1 on 2026-02-02 08:44

from django.db import migrations, models

import pretalx.event.models.event


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0040_alter_event_settingsstore_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="og_image",
            field=models.ImageField(
                null=True, upload_to=pretalx.event.models.event.event_og_path
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="header_image",
            field=models.ImageField(
                null=True, upload_to=pretalx.event.models.event.event_header_path
            ),
        ),
    ]
