# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.5 on 2026-05-10 05:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("event", "0041_event_og_image")]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="event_slug_lower_unique",
            ),
        )
    ]
