# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.5 on 2026-05-20 12:09

from django.db import migrations, models

import pretalx.event.models.event


class Migration(migrations.Migration):
    dependencies = [("event", "0042_event_event_slug_lower_unique")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendee_signup_settings",
            field=models.JSONField(
                default=pretalx.event.models.event.default_attendee_signup_settings
            ),
        )
    ]
