# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.7 on 2026-07-30 10:46

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("event", "0044_event_locales_json")]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                django.db.models.functions.text.Upper("slug"),
                name="event_slug_upper_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organiser",
            index=models.Index(
                django.db.models.functions.text.Upper("slug"),
                name="organiser_slug_upper_idx",
            ),
        ),
    ]
