# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.1 on 2026-09-04 15:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("event", "0045_event_event_slug_upper_idx_and_more")]

    operations = [
        migrations.AddConstraint(
            model_name="organiser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="organiser_slug_lower_unique",
            ),
        )
    ]
