# Generated by Django 5.2.3 on 2025-06-10 12:43

import django.db.models.deletion
import i18nfield.fields
import pretalx.common.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("schedule", "0001_initial"),
        ("schedule", "0002_auto_20170523_0134"),
        ("schedule", "0003_auto_20170523_1144"),
        ("schedule", "0004_auto_20170715_0655"),
        ("schedule", "0005_schedule_published"),
        ("schedule", "0006_talkslot_is_visible"),
        ("schedule", "0007_auto_20170806_0931"),
        ("schedule", "0008_auto_20170916_0421"),
        ("schedule", "0009_auto_20171001_0433"),
        ("schedule", "0010_auto_20171001_1358"),
        ("schedule", "0010_auto_20171001_0439"),
        ("schedule", "0011_auto_20180205_1127"),
        ("schedule", "0012_auto_20190303_2358"),
        ("schedule", "0013_auto_20191107_1748"),
        ("schedule", "0014_schedule_comment"),
        ("schedule", "0015_room_guid"),
        ("schedule", "0016_talkslot_updated"),
        ("schedule", "0017_created_updated_everywhere"),
    ]

    dependencies = [
        ("event", "0039_alter_teaminvite_token"),
        ("person", "0031_migrate_auth_tokens"),
        ("submission", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", i18nfield.fields.I18nCharField(max_length=100)),
                (
                    "description",
                    i18nfield.fields.I18nCharField(
                        blank=True, max_length=1000, null=True
                    ),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="event.event",
                    ),
                ),
                (
                    "speaker_info",
                    i18nfield.fields.I18nCharField(
                        blank=True, max_length=1000, null=True
                    ),
                ),
                ("guid", models.UUIDField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ("position",),
                "unique_together": {("event", "guid")},
            },
            bases=(pretalx.common.models.mixins.LogMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=190, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="event.event",
                    ),
                ),
                ("published", models.DateTimeField(blank=True, null=True)),
                ("comment", i18nfield.fields.I18nTextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "unique_together": {("event", "version")},
                "ordering": ("-published",),
            },
            bases=(pretalx.common.models.mixins.LogMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="event.event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="person.speakerprofile",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="schedule.room",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            bases=(pretalx.common.models.mixins.LogMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TalkSlot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("start", models.DateTimeField(null=True)),
                ("end", models.DateTimeField(null=True)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="talks",
                        to="schedule.room",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="talks",
                        to="schedule.schedule",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="submission.submission",
                    ),
                ),
                ("is_visible", models.BooleanField(default=False)),
                ("description", i18nfield.fields.I18nCharField(null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "unique_together": set(),
            },
            bases=(pretalx.common.models.mixins.LogMixin, models.Model),
        ),
    ]
