# Generated by Django 1.10.7 on 2017-05-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talkslot",
            name="end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="talkslot",
            name="start",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("event", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="talkslot",
            unique_together={("submission", "schedule")},
        ),
    ]
