# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 1.11.3 on 2017-07-15 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_auto_20170523_1144"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ("position",)},
        ),
    ]
