# SPDX-FileCopyrightText: 2023 pretalx contributors <https://github.com/pretalx/pretalx/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 1.11.3 on 2017-07-15 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_auto_20170523_1144"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ("position",)},
        ),
    ]
