# SPDX-FileCopyrightText: 2018-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 2.0.1 on 2018-02-05 17:27

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0010_auto_20171001_0439"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="speaker_info",
            field=i18nfield.fields.I18nCharField(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=i18nfield.fields.I18nCharField(
                blank=True, max_length=1000, null=True
            ),
        ),
    ]
