# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 2.2.4 on 2019-11-07 17:48

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0012_auto_20190303_2358"),
    ]

    operations = [
        migrations.AddField(
            model_name="talkslot",
            name="description",
            field=i18nfield.fields.I18nCharField(null=True),
        ),
        migrations.AlterField(
            model_name="talkslot",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="slots",
                to="submission.Submission",
            ),
        ),
    ]
