# Generated by Django 3.1.4 on 2021-06-06 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0014_schedule_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="guid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
