# SPDX-FileCopyrightText: 2021-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 3.2.4 on 2021-11-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0026_team_force_hide_speaker_names"),
        ("schedule", "0014_schedule_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="guid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("event", "guid")},
        ),
    ]
