# Generated by Django 3.1.4 on 2021-06-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_event_featured_sessions_text'),
        ('schedule', '0015_room_guid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('event', 'guid')},
        ),
    ]
