# SPDX-FileCopyrightText: 2023 pretalx contributors <https://github.com/pretalx/pretalx/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 3.2.4 on 2021-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0015_room_guid"),
    ]

    operations = [
        migrations.AddField(
            model_name="talkslot",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
