# SPDX-FileCopyrightText: 2023-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 4.2.4 on 2023-10-03 16:42
from django.db import migrations, models

import pretalx.common.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0016_talkslot_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="availability",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="talkslot",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="talkslot",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="talkslot",
            name="end",
            field=pretalx.common.models.fields.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="talkslot",
            name="start",
            field=pretalx.common.models.fields.DateTimeField(null=True),
        ),
    ]
