# Generated by Django 3.2.12 on 2022-05-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0068_alter_reviewscore_value"),
        ("schedule", "0016_talkslot_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="cfp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="submission.cfp",
            ),
        ),
    ]
