# SPDX-FileCopyrightText: 2025-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0 on 2025-12-12 09:48

from django.db import migrations, models


def set_existing_breaks(apps, schema_editor):
    """Set slot_type='break' for existing slots without a submission (i.e., breaks)."""
    TalkSlot = apps.get_model("schedule", "TalkSlot")
    TalkSlot.objects.filter(submission__isnull=True).update(slot_type="break")


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0017_created_updated_everywhere"),
    ]

    operations = [
        migrations.AddField(
            model_name="talkslot",
            name="slot_type",
            field=models.CharField(
                blank=True,
                choices=[("break", "Break"), ("blocker", "Blocker")],
                help_text="For non-submission slots: 'break' for public breaks, 'blocker' for hidden blockers",
                max_length=10,
                null=True,
                verbose_name="Slot type",
            ),
        ),
        migrations.RunPython(set_existing_breaks, migrations.RunPython.noop),
    ]
