# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.7 on 2026-08-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("schedule", "0019_room_hidden")]

    operations = [
        migrations.AddField(
            model_name="room",
            name="parallel_sessions",
            field=models.BooleanField(default=False),
        )
    ]
