# SPDX-FileCopyrightText: 2022-present Tobias Kunze
# SPDX-License-Identifier: CC-BY-SA-4.0

blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/pretalx/pretalx/discussions
    about: Please post your support requests in our GitHub Discussions instead!
