# SPDX-FileCopyrightText: 2022-present Tobias Kunze
# SPDX-License-Identifier: CC-BY-SA-4.0

name: Feature idea
description: Suggest a new pretalx feature.
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: Please make sure to search our issues for similar feature requests first! If the requests exists already, react with a thumbs-up to indicate your interest. If a similar issue exists, either leave a comment there or link the issue here.
  - type: textarea
    id: problem
    attributes:
      label: Problem and impact
      description: What problem you're running into? What impact does it have on you / your event?
      placeholder: "When trying to do ____, I have to go through three separate pages: …"
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution / feature
      description: How would pretalx behave in an ideal world? What would make your life easier?
      placeholder: Ideally, I could do ____ directly from page ____, with helpful suggestions drawing from my recent search.
  - type: textarea
    id: context
    attributes:
      label: Context or examples
      description: Providing context helps us choose a solution that is the most useful to all events using pretalx while also being maintainable. Examples from other projects, or screenshots, or rough drafts are also great to start a discussion.
