# Generated by Django 5.2.3 on 2025-06-10 12:41

import django.db.models.deletion
import pretalx.common.models.file
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("common", "0002_auto_20170429_1018"),
        ("common", "0003_activitylog_is_orga_action"),
        ("common", "0004_auto_20170526_0437"),
        ("common", "0005_auto_20180202_1116"),
        ("common", "0006_cachedfile"),
    ]

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="log_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="is_orga_action",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="log_entries",
                to="event.event",
            ),
        ),
        migrations.CreateModel(
            name="CachedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("expires", models.DateTimeField()),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=255)),
                ("session_key", models.TextField(null=True)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        null=True,
                        upload_to=pretalx.common.models.file.cachedfile_name,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires"], name="common_cach_expires_d8715c_idx"
                    )
                ],
            },
        ),
    ]
