# SPDX-FileCopyrightText: 2023 pretalx contributors <https://github.com/pretalx/pretalx/graphs/contributors>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 1.10.7 on 2017-05-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_auto_20170429_1018"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="is_orga_action",
            field=models.BooleanField(default=False),
        ),
    ]
