# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 1.10.7 on 2017-05-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_auto_20170429_1018"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="is_orga_action",
            field=models.BooleanField(default=False),
        ),
    ]
