# Generated by Django 2.0.1 on 2018-02-02 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_auto_20170526_0437"),
    ]

    operations = []
