# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.1 on 2026-09-10 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_activitylog_profile_email_rename"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("event", "0046_organiser_organiser_slug_lower_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["event", "-timestamp", "-id"], name="activitylog_event_ts_idx"
            ),
        )
    ]
