# Generated by Django 5.2.3 on 2025-06-10 12:42

import django.db.models.deletion
import i18nfield.fields
import pretalx.common.models.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("mail", "0001_initial"),
        ("mail", "0002_queuedmail_sent"),
        ("mail", "0003_auto_20171001_1358"),
        ("mail", "0004_auto_20190222_2215"),
        ("mail", "0005_queuedmail_to_users"),
        ("mail", "0006_populate_mail_users"),
        ("mail", "0007_auto_20190327_2241"),
        ("mail", "0008_auto_20210830_2352"),
        ("mail", "0009_queuedmail_locale"),
        ("mail", "0010_queuedmail_attachments"),
        ("mail", "0011_created_updated_everywhere"),
        ("mail", "0012_queuedmail_submissions"),
        ("mail", "0013_mailtemplate_role"),
    ]

    dependencies = [
        ("event", "0001_initial"),
        ("person", "0001_initial"),
        ("submission", "0077_answeroption_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("subject", i18nfield.fields.I18nCharField(max_length=200)),
                ("text", i18nfield.fields.I18nTextField()),
                ("reply_to", models.CharField(blank=True, max_length=200, null=True)),
                ("bcc", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mail_templates",
                        to="event.event",
                    ),
                ),
                ("is_auto_created", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            bases=(pretalx.common.models.mixins.LogMixin, models.Model),
        ),
        migrations.CreateModel(
            name="QueuedMail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("to", models.CharField(blank=True, max_length=1000, null=True)),
                ("reply_to", models.CharField(blank=True, max_length=1000, null=True)),
                ("cc", models.CharField(blank=True, max_length=1000, null=True)),
                ("bcc", models.CharField(blank=True, max_length=1000, null=True)),
                ("subject", models.CharField(max_length=200)),
                ("text", models.TextField()),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queued_mails",
                        to="event.event",
                    ),
                ),
                ("sent", models.DateTimeField(blank=True, null=True)),
                (
                    "to_users",
                    models.ManyToManyField(
                        related_name="mails", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mails",
                        to="mail.mailtemplate",
                    ),
                ),
                ("locale", models.CharField(max_length=32, null=True)),
                ("attachments", models.JSONField(default=None, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "submissions",
                    models.ManyToManyField(
                        related_name="mails", to="submission.submission"
                    ),
                ),
            ],
            bases=(pretalx.common.models.mixins.LogMixin, models.Model),
        ),
    ]
