# Generated by Django 2.1.7 on 2019-03-27 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0005_queuedmail_to_users"),
    ]

    operations = []
