# SPDX-FileCopyrightText: 2019-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 3.2.4 on 2021-08-30 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0007_auto_20190327_2241"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailtemplate",
            name="is_auto_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queuedmail",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mails",
                to="mail.mailtemplate",
            ),
        ),
    ]
