# Generated by Django 5.1.2 on 2024-10-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0011_created_updated_everywhere"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedmail",
            name="headers",
            field=models.JSONField(default=None, null=True),
        ),
    ]
