# Generated by Django 5.1.3 on 2024-12-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0012_queuedmail_submissions"),
    ]

    operations = []
