# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.4 on 2026-04-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("mail", "0014_queuedmail_state_error")]

    operations = [
        migrations.AddField(
            model_name="queuedmail",
            name="text_html",
            field=models.TextField(null=True, blank=True),
        )
    ]
