# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms

# Generated by Django 6.0.7 on 2026-07-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0016_replace_notifications_placeholder"),
        ("person", "0046_speakerprofile_guid_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedmail",
            name="to_speakers",
            field=models.ManyToManyField(
                related_name="mails", to="person.speakerprofile"
            ),
        )
    ]
