# Generated by Django 6.0.7 on 2026-07-31 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("mail", "0018_backfill_to_speakers")]

    operations = [migrations.RemoveField(model_name="queuedmail", name="to_users")]
