# SPDX-FileCopyrightText: 2026-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Pretalx-AGPL-3.0-Terms
from tests.factories.common import ActivityLogFactory, CachedFileFactory
from tests.factories.event import (
    EventExtraLinkFactory,
    EventFactory,
    OrganiserFactory,
    TeamFactory,
    TeamInviteFactory,
)
from tests.factories.mail import MailTemplateFactory, QueuedMailFactory
from tests.factories.person import (
    ProfilePictureFactory,
    SpeakerFactory,
    SpeakerInformationFactory,
    UserApiTokenFactory,
    UserEventPreferencesFactory,
    UserFactory,
)
from tests.factories.schedule import (
    AvailabilityFactory,
    RoomFactory,
    ScheduleFactory,
    TalkSlotFactory,
)
from tests.factories.submission import (
    AnswerFactory,
    AnswerOptionFactory,
    FeedbackFactory,
    QuestionFactory,
    ResourceFactory,
    ReviewFactory,
    ReviewPhaseFactory,
    ReviewScoreCategoryFactory,
    ReviewScoreFactory,
    SpeakerRoleFactory,
    SubmissionCommentFactory,
    SubmissionFactory,
    SubmissionFavouriteFactory,
    SubmissionInvitationFactory,
    SubmissionTypeFactory,
    SubmitterAccessCodeFactory,
    TagFactory,
    TrackFactory,
)

__all__ = [
    "ActivityLogFactory",
    "CachedFileFactory",
    "AnswerFactory",
    "AnswerOptionFactory",
    "AvailabilityFactory",
    "EventExtraLinkFactory",
    "EventFactory",
    "FeedbackFactory",
    "MailTemplateFactory",
    "OrganiserFactory",
    "ProfilePictureFactory",
    "QueuedMailFactory",
    "QuestionFactory",
    "ResourceFactory",
    "ReviewFactory",
    "ReviewPhaseFactory",
    "ReviewScoreCategoryFactory",
    "ReviewScoreFactory",
    "RoomFactory",
    "ScheduleFactory",
    "SpeakerFactory",
    "SpeakerInformationFactory",
    "SpeakerRoleFactory",
    "SubmissionCommentFactory",
    "SubmissionFactory",
    "SubmissionFavouriteFactory",
    "SubmissionInvitationFactory",
    "SubmissionTypeFactory",
    "SubmitterAccessCodeFactory",
    "TagFactory",
    "TalkSlotFactory",
    "TeamFactory",
    "TeamInviteFactory",
    "TrackFactory",
    "UserApiTokenFactory",
    "UserEventPreferencesFactory",
    "UserFactory",
]
